SELECT PLAYERNO FROM PLAYERS WHERE JOINED > 1980 AND TOWN = 'Stratford' ORDER BY PLAYERNO;
SELECT * FROM PENALTIES;
SELECT NAME FROM players WHERE JOINED > 1980 AND TOWN = 'Stratford' ORDER BY PLAYERNO;
SELECT * FROM teams;
SHOW tables;